name: Deploy dbt docs to GitHub Pages


on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dbt
      run: pip install dbt-snowflake

    - name: Set up dbt profile
      run: |
        mkdir -p ~/.dbt
        echo "
        gmds_demo_aws:
          target: prod
          outputs:
            prod:
              type: snowflake
              threads: 14
              account: vi27304.uk-south.azure
              database: TASTY_BYTES_SAMPLE_DATA
              role: ACCOUNTADMIN
              schema: TASTY_BYTES_SAMPLE_DATA
              warehouse: COMPUTE_WH
              user: ${{ secrets.SNOWFLAKE_USER }}
              password: ${{ secrets.SNOWFLAKE_PASS }}
        " > ~/.dbt/profiles.yml      

    - name: Install dependancies
      run: dbt deps
      
    - name: Generate dbt docs
      run: dbt docs generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: ./target
